repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        language: system
        entry: isort
        types: [python]

      - id: black
        name: black
        language: system
        entry: black
        types: [python]

      - id: flake8
        name: flake8
        language: system
        entry: flake8
        types: [python]
        exclude: migrations
